---
- name: Install Vim
  become: true
  apt:
    name: vim
    state: present
    update_cache: yes

- name: Create .vim/bundle directory
  file:
    path: "{{ ansible_env.HOME }}/.vim/bundle"
    state: directory
    mode: '0755'

- name: Install Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
    update: no

- name: Copy vimrc configuration
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0644'
...